# Generated by Django 5.1.6 on 2025-02-13 19:22

import cinema.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to=cinema.utils.custom_movie_image_path),
        ),
    ]
